# Generated by Django 3.2.3 on 2021-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
