# Generated by Django 3.2.5 on 2021-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0011_pronote_last_token_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profabsent',
            old_name='name',
            new_name='teacher',
        ),
    ]
