# Generated by Django 3.2.3 on 2021-10-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0012_rename_name_profabsent_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pronote',
        ),
    ]
