# Generated by Django 3.2.5 on 2022-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(default='', null=True, upload_to='Users/profile_pictures/'),
        ),
    ]
