# Generated by Django 3.2.3 on 2022-03-03 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screens',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5c3bc395-db7f-4e6f-b7aa-61e6b9e5bf84'), max_length=100),
        ),
    ]
