# Generated by Django 3.2.5 on 2022-01-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0002_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_last_modif',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
