# Generated by Django 3.2.3 on 2021-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0003_alter_sondage_est_affiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='date_creation',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
