# Generated by Django 3.2.7 on 2021-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0005_auto_20210915_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='code_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
