# Generated by Django 3.2.5 on 2021-10-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0006_display_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PartieduRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repas_midi', models.BooleanField()),
                ('date', models.DateField()),
                ('aliments_du_repas', models.ManyToManyField(to='ApiServer.Aliment')),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='partie_du_repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServer.partiedurepas'),
        ),
    ]
