# Generated by Django 3.2.5 on 2021-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0007_auto_20211021_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
