# Generated by Django 3.2.5 on 2021-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0008_alter_aliment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_query', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
