# Generated by Django 3.2.5 on 2021-10-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0009_pronote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfAbsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
    ]
