# Generated by Django 3.2.5 on 2021-10-23 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0010_profabsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronote',
            name='last_token_query',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
