# Generated by Django 3.2.3 on 2021-11-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0013_delete_pronote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_created=True, auto_now=True)),
                ('question', models.CharField(max_length=50)),
                ('date_fin', models.DateTimeField()),
                ('est_affiché', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServer.sondage')),
            ],
        ),
    ]
