# Generated by Django 3.2.3 on 2021-11-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0014_reponse_sondage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sondage',
            old_name='est_affiché',
            new_name='est_affiche',
        ),
    ]
