# Generated by Django 3.2.3 on 2021-11-23 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0015_rename_est_affiché_sondage_est_affiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ApiServer.sondage'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ApiServer.reponse')),
            ],
        ),
    ]
