# Generated by Django 3.2.3 on 2021-11-23 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0016_auto_20211123_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='sondage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiServer.sondage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aliment',
            name='partie_du_repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ApiServer.partiedurepas'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServer.sondage'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServer.reponse'),
        ),
    ]
